#!/bin/bash

# GPIO numbers
BOOT0=17
RST=23
GPIOCHIP=0

echo "Initializing GPIOs..."

# Initialize BOOT0 to low
timeout 1s gpioset -c gpiochip${GPIOCHIP} ${BOOT0}=0

# Initialize RST to high
timeout 1s gpioset -c gpiochip${GPIOCHIP} ${RST}=1
